Rely on cascading deletes in ResourceDefinitionService.deleteByUuid
Mixing up manual deletions with cascade deletions in transactional methods leads to errors like below:

>org.hibernate.TransientObjectException: persistent instance references an unsaved transient instance of 'org.fairdatapoint.entity.resource.ResourceDefinition'

Either consistently use cascading (as it is used throughout the existing codebase), or don't do it at all.