SPARQL proxy endpoint (experimental) (#898)
Squashed the following commits:

* add a RestClient bean

  RestTemplate is deprecated, so we're using RestClient for new functionality.
  Existing functionality using RestTemplate should be updated in a separate PR, see #897

* add RestClient to SearchSparqlController (wip)

* add a rudimentary proxySparqlEndpoint (wip)

  The idea is to pass on requests as unauthenticated requests to the triple store's SPARQL endpoint.

* add response to proxySparqlEndpoint

  Here we use RestClient.exchange() to obtain the actual response object, with body as bytes to ensure it remains unchanged.
  Note that RestClient.retrieve() could work, but that would raise an error if the RestClient receives a status >=400, so the controller would return a status 500 server error.

* move endpoint url logic into separate determineSparqlEndpointUrl method

* remove hop-by-hop headers from sparql endpoint response (wip)

* move response header cleanup to separate cleanHeaders() method

* rename cleanHeaders to cleanResponseHeaders

* fix checkstyle errors

* forward request headers to backend triple store

* convert adaptRequestHeaders into a factory method requestHeadersUpdater (this is a better fit for the restclient headers() method api)

* simplify requestHeadersUpdater with the help of @RequestHeader (this is a more idiomatic spring web mvc approach, although we still need to use the underlying request object to get the ip)

* rename request/response variables for clarity

* replace requestHeadersUpdater by lambda (due to the @RequestHeader approach, it is now cleaner to use the lambda)

* add sparql uri query parameters (the url parameters are added separately, instead of using a map containing all of them, because this creates more useful swagger docs)

* rudimentary test for sparql GET (wip)

* make getSparqlUnauthenticated test conditional and evaluate response

* require authentication for proxySparqlEndpoint and adapt tests accordingly

* replace old sparqlPost endpoint by new proxySparqlEndpoint (disable the endpoint if there is no external triple store, using @Conditional, and remove the dependency on rdf4j sparqlQueryEvaluator etc.)

* replace custom NoneNestedConditions by a ConditionalOnExpression for SearchSparqlController

* replace determineSparqlEndpointUrl by RepositoryProperties.getUrl

* remove condition from SearchSparqlController and return 404 instead

* dry path in sparql controller test

* start adapting sparql controller tests (wip)

* mark sparql proxy endpoint as experimental in api docs

* remove authorization header from sparql proxy request

* rename TestSearchSparqlController to SearchSparqlControllerTest for consistence

* rename TestSearchSparqlController to SearchSparqlControllerTest for consistence

* remove unused imports from sparql controller test

* use mock user for sparql controller tests

* rename sparql controller test methods

* switch from webmvctest to springboottest because the former requires too much mocking and config imports

* annotate HttpClientConfig with Profiles.NON_TESTING

* configure MockRestServiceServer for sparql tests (wip)

* revert adding Profiiles.NON_TESTING to HttpClientConfig (this is no longer necessary after removing the unused HttpClient bean in #910)

* mock RestTemplate in SearchSparqlControllerTest and remove test config for RestClient (after #910 this is sufficient to prevent conflicts durign auto config of the MockRestServiceServer)

* create RestClient bean using builder (this is required for the MockRestServiceServer autoconfiguration to work)

* fix mock sparql server expected url

* rename mockRemoteSparqlServer to mockBackendSparqlServer

* put hop-by-hop headers into class constant with public getter

* add request expectations for sparql proxy test

* add mock response headers and response expectations for sparql proxy test

* rename sparql proxy test method

* test that proxy returns the json results body from a sparql query

* make sparql proxy controller optional (opt-in via intance.sparqlProxyEnabled property)

* disable checkstyle ExplicitInitialization (this check is only a very minor optimization, and I value explicitness over implicitness)

* make sparqlEndpointUrl check reusable

* make request header cleanup reusable

* docstring for returnIfSparqlEndpointUnavailable

* rename sparql controller get method and corresponding test

* make response cleanup exchange function reusable

* rename cleanRequestHeaders to cleanRequestHeadersFactory

* explicitly expect GET request and verify that mock server received expected requests

* newlines in test

* use constants for sparql protocol parameter names

* move mockJsonBody from tests method to class level

* add sparql proxy POST mapping for form data (wip)

* get sparqlEndpointUrl from Repository instead of RepositoryProperties (the latter returned an incomplete url, without the repository path...)

* rename returnIfSparqlEndpointUnavailable to abortIf... and also abort if url is empty

* make MultiValueMap mutable

* add example sparql query to api-docs and fix checkstyle issues

* use ReflectionTestUtils to override sparqlEndpointUrl in tests

* fix MultiValueMap mutability

  By using MultiValueMap we prevent the error
  'No HttpMessageConverter for java.util.HashMap and content type "application/x-www-form-urlencoded;charset=UTF-8"'
  However, now we're back at the earlier problem:
  'Content type expected:<application/x-www-form-urlencoded> but was:<application/x-www-form-urlencoded;charset=UTF-8>'

* fix mock server content type expectation for sparql form post (this ensures the mock server also accepts content-type with charset=UTF-8 appended)

* add all possible sparql query response types to controller methods (among other things, this enables selection of content-type in openapi docs)

* Revert "add all possible sparql query response types to controller methods" because there is probably a cleaner way to achieve this for all endpoints

* add sparl proxy post method for raw sparql (wip)

* add test for sparql proxy post raw query

* update proxy sparl method comments

* fix hashmap type

* replace CollectionUtils by MultiValueMap in tests

* abort sparql proxy post request if it contains an update field

* introduce constants for sparql-query and sparql-update media types

* abort raw post request if content-type is sparql-update

* rename sparql post test methods and reuse sparql-query media type

* remove debug log message

* Revert "abort raw post request if content-type is sparql-update" because this is already handled by the @PostMapping consumes argument

* test that sparql-update content-type is denied

* throw ResponseStatusException instead of returning ResponseEntity

* use PARAM_QUERY in test

* introduce HEADER_X_FORWARDED_FOR constant

* add sparql query validation to sparql proxy endpoint

* bump package version from 1.19.1 to 1.20.0 (sparql protocol support is a new feature)

* rename sparql test methods for consistency

* move sparql query validation into separate SparqlQueryValidator class

* add tests for SparqlQueryValidator

* move sparql proxy cleaning methods into separate SparqlProxyHeaderCleaner class

* rename SearchSparqlController to SparqlProxyController and same for test class

* rename SparqlProxyHeaderCleaner to SparqlProxyCleaningService

* clean up docstrings for SparqlProxyController

* switch method signature from ConvertibleClientHttpResponse to ClientHttpResponse

* clean up SparqlProxyControllerTest and move header stuff into SparqlProxyCleaningServiceTest

* remove unnecessary UriComponentsBuilder use from SparqProxyControllerTest

* add URL validation for SparqlProxyController graph-uri parameters

* note about @ValidIri

* clean up debug leftovers